### RigUI Script generated by Bone Layers Addon ###

import bpy

blm_rig_id = "o3650ofql28m"


class BLOP_PT_rigui_o3650ofql28m(bpy.types.Panel):
	bl_space_type = 'VIEW_3D'
	bl_region_type = 'UI'
	bl_category = 'Item'
	bl_label = "Rig UI"
	bl_idname = "BLOP_PT_rigui_o3650ofql28m"

	@classmethod
	def poll(self, context):
		try:
			return (context.active_object.data.get("blm_rig_id") == blm_rig_id)
		except (AttributeError, KeyError, TypeError):
			return False

	def draw(self, context):
		layout = self.layout
		col = layout.column()
		collection = bpy.data.armatures["PUNCHING-BAG-Armature"].collections


		row = col.row()
		row.prop(collection["Layer 9 - ROOT"],'is_visible', toggle=True, text='ROOT')

		row = col.row()
		row.prop(collection["Layer 10 - MASTER"],'is_visible',  toggle=True, text='MASTER')

		row = col.row()
		row.prop(collection["Layer 11 - BAG"],'is_visible',  toggle=True, text='BAG')

		row = col.row()
		row.prop(collection["Layer 12 - TWEAK"],'is_visible',  toggle=True, text='TWEAK')



classes = (BLOP_PT_rigui_o3650ofql28m, )

register, unregister = bpy.utils.register_classes_factory(classes)

if __name__ == "__main__":
	register()