### RigUI Script generated by Bone Layers Addon ###

import bpy

blm_rig_id = "ziql7v79y6x1"


class BLOP_PT_rigui_ziql7v79y6x1(bpy.types.Panel):
	bl_space_type = 'VIEW_3D'
	bl_region_type = 'UI'
	bl_category = 'Item'
	bl_label = "Rig UI"
	bl_idname = "BLOP_PT_rigui_ziql7v79y6x1"

	@classmethod
	def poll(self, context):
		try:
			return (context.active_object.data.get("blm_rig_id") == blm_rig_id)
		except (AttributeError, KeyError, TypeError):
			return False

	def draw(self, context):
		layout = self.layout
		col = layout.column()
		collection = bpy.data.armatures["Armature"].collections

		row = col.row()
		row.prop(collection["Layer 9 - ROOT"],'is_visible',toggle=True, text='ROOT')

		row = col.row()
		row.prop(collection["Layer 10 - TORSO"],'is_visible', toggle=True, text='TORSO')

		row = col.row()
		row.prop(collection["Layer 11 - ARMS"],'is_visible', toggle=True, text='ARMS')
		row.prop(collection["Layer 12 - ROCKETS"],'is_visible', toggle=True, text='ROCKETS')
		row.prop(collection["Layer 13 - MINIGUN"],'is_visible', toggle=True, text='MINIGUN')

		row = col.row()
		row.prop(collection["Layer 14 - LEGS-FK"],'is_visible', toggle=True, text='LEGS-FK')

		row = col.row()
		row.prop(collection["Layer 15 - LEGS-IK"],'is_visible', toggle=True, text='LEGS-IK')


class BLOP_PT_rigproperties_ziql7v79y6x1(bpy.types.Panel):
    bl_label = "RIG Properties" 
    bl_idname = "BLOP_PT_rigproperties_ziql7v79y6x1"
    bl_space_type = 'VIEW_3D'
    bl_category = 'Item'
    bl_region_type = 'UI'
    bl_options = {'DEFAULT_CLOSED'} # you may not want this? delete if not
    
    def draw(self, context):
        
        # get armature and "PROPERTIES" bone 
        arm = context.active_object
        bone = arm.pose.bones["PROPERTIES"]
        
        # basic layout setup
        layout = self.layout
        # just in we case want to change the split makes make a variable
        split_size = 0.7
        
        # then we start making rows        
        box = layout.box()
        col = box.column(align=True)
        row = col.row()              
        split = row.split(align=True, factor=split_size)
        row = split.row(align=True)        
        # this is just the label you could call it anything
        row.label(text='FK-IK.L', translate=False)
        row = split.row(align=True)
        # this is the property > format is important
        row.prop(bone, '["FK-IK.L"]', text = "", slider=True)
        
        # copy paste repeat... test as you go
        row = col.row() 
        split = row.split(align=True, factor=split_size)
        row = split.row(align=True)
        row.label(text='FK-IK.R', translate=False)
        row = split.row(align=True)
        row.prop(bone, '["FK-IK.R"]', text = "", slider=True)
        
                # copy paste repeat... test as you go
        row = col.row() 
        split = row.split(align=True, factor=split_size)
        row = split.row(align=True)
        row.label(text='Follow leg.L', translate=False)
        row = split.row(align=True)
        row.prop(bone, '["FOLLOW-LEG.L"]', text = "", slider=True)
                # copy paste repeat... test as you go
        row = col.row() 
        split = row.split(align=True, factor=split_size)
        row = split.row(align=True)
        row.label(text='Follow leg.R', translate=False)
        row = split.row(align=True)
        row.prop(bone, '["FOLLOW-LEG.R"]', text = "", slider=True)
     
        box = layout.box()
        col = box.column(align=True)
        row = col.row()              
        split = row.split(align=True, factor=split_size)
        row = split.row(align=True)  
        row = col.row() 
        split = row.split(align=True, factor=split_size)
        row = split.row(align=True)
        row.label(text='Follow arm.L', translate=False)
        row = split.row(align=True)
        row.prop(bone, '["FOLLOW-ARM.L"]', text = "", slider=True)
        
                # copy paste repeat... test as you go
        row = col.row() 
        split = row.split(align=True, factor=split_size)
        row = split.row(align=True)
        row.label(text='Follow arm.R', translate=False)
        row = split.row(align=True)
        row.prop(bone, '["FOLLOW-ARM.R"]', text = "", slider=True)
        
         # then we start making rows        
        box = layout.box()
        col = box.column(align=True)
        row = col.row()              
        split = row.split(align=True, factor=split_size)
        row = split.row(align=True)        
        # this is just the label you could call it anything
        row.label(text='Follow artillery', translate=False)
        row = split.row(align=True)
        # this is the property > format is important
        row.prop(bone, '["FOLLOW-ARTILLERY"]', text = "", slider=True)
        
        # copy paste repeat... test as you go
        row = col.row() 
        split = row.split(align=True, factor=split_size)
        row = split.row(align=True)
        row.label(text='follow head', translate=False)
        row = split.row(align=True)
        row.prop(bone, '["FOLLOW-HEAD"]', text = "", slider=True)
        
                # copy paste repeat... test as you go
        row = col.row() 
        split = row.split(align=True, factor=split_size)
        row = split.row(align=True)
        row.label(text='follow Sensor', translate=False)
        row = split.row(align=True)
        row.prop(bone, '["FOLLOW-SENSOR"]', text = "", slider=True)
        
                # copy paste repeat... test as you go
        row = col.row() 
        split = row.split(align=True, factor=split_size)
        row = split.row(align=True)
        row.label(text='follow minigun', translate=False)
        row = split.row(align=True)
        row.prop(bone, '["FOLLOW-MINIGUN"]', text = "", slider=True)
        
class BLOP_PT_rigvisibility_ziql7v79y6x1(bpy.types.Panel):
    bl_label = "RIG Visibiility" 
    bl_idname = "BLOP_PT_rigvisibility_ziql7v79y6x1"
    bl_space_type = 'VIEW_3D'
    bl_category = 'Item'
    bl_region_type = 'UI'
    bl_options = {'DEFAULT_CLOSED'} # you may not want this? delete if not
    
    def draw(self, context):
        
        # get armature and "VIEW-PROPERTIES" bone 
        arm = context.active_object
        bone = arm.pose.bones["VIEW-PROPERTIES"]
        
        # basic layout setup
        layout = self.layout
        # just in we case want to change the split makes make a variable
        split_size = 0.7
        
        # then we start making rows        
        box = layout.box()
        col = box.column(align=True)
        row = col.row()              
        split = row.split(align=True, factor=split_size)
        row = split.row(align=True)        
        # this is just the label you could call it anything
        row.label(text='Bevel', translate=False)
        row = split.row(align=True)
        # this is the property > format is important
        row.prop(bone, '["BEVEL"]', text = "", slider=True)
        
        # copy paste repeat... test as you go
        row = col.row() 
        split = row.split(align=True, factor=split_size)
        row = split.row(align=True)
        row.label(text='Artillery', translate=False)
        row = split.row(align=True)
        row.prop(bone, '["MASK-ARTILLERY"]', text = "", slider=True)
        
                # copy paste repeat... test as you go
        row = col.row() 
        split = row.split(align=True, factor=split_size)
        row = split.row(align=True)
        row.label(text='Legs', translate=False)
        row = split.row(align=True)
        row.prop(bone, '["MASK-LEG"]', text = "", slider=True)
                # copy paste repeat... test as you go
        row = col.row() 
        split = row.split(align=True, factor=split_size)
        row = split.row(align=True)
        row.label(text='Minigun', translate=False)
        row = split.row(align=True)
        row.prop(bone, '["MASK-MINIGUN"]', text = "", slider=True)
                        # copy paste repeat... test as you go
        row = col.row() 
        split = row.split(align=True, factor=split_size)
        row = split.row(align=True)
        row.label(text='Rocket', translate=False)
        row = split.row(align=True)
        row.prop(bone, '["MASK-ROCKET"]', text = "", slider=True)
                        # copy paste repeat... test as you go
        row = col.row() 
        split = row.split(align=True, factor=split_size)
        row = split.row(align=True)
        row.label(text='Subdiv Level', translate=False)
        row = split.row(align=True)
        row.prop(bone, '["SUBDIV"]', text = "", slider=True)
     

classes = (BLOP_PT_rigui_ziql7v79y6x1, BLOP_PT_rigproperties_ziql7v79y6x1,BLOP_PT_rigvisibility_ziql7v79y6x1)

register, unregister = bpy.utils.register_classes_factory(classes)

if __name__ == "__main__":
	register()